/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Hylly_ovi_pieni.gltf --transform -j 
Files: Hylly_ovi_pieni.gltf [30.86KB] > C:\Users\Remes\hooli\CAD\Hylly_ovi_pieni-transformed.glb [44.89KB] (-45%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Hylly_ovi_pieni-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.015, 0.013, -0.013]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Left_door_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Left_door_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Left_door_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Left_door_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Left_door_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Left_door_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.375, 0.013, -0.013]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Right_door_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Right_door_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Right_door_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Right_door_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Right_door_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Right_door_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[0, 0.183, -0.23]}>
        <mesh geometry={nodes.attach_left_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_left_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_left_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_left_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_left_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_left_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.73, 0.183, -0.23]}>
        <mesh geometry={nodes.attach_right_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_right_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_right_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_right_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_right_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_right_6.geometry} material={materials.mat_0} />
      </group>
      <mesh geometry={nodes.runkoObj_1.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_2.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_3.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_4.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_5.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_6.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_7.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_8.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_9.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_10.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_11.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_12.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_13.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_14.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_15.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_16.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_17.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_18.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_19.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_20.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_21.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_22.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_23.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_24.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_25.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_26.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_27.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_28.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_29.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_30.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_31.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_32.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_33.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_34.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_35.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_36.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_37.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_38.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_39.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_40.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_41.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_42.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_43.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_44.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_45.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_46.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_47.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_48.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_49.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.runkoObj_50.geometry} material={materials.mat_0} />
    </group>
  )
}

useGLTF.preload('/Hylly_ovi_pieni-transformed.glb')
