/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Shelf_001.glb --transform -j 
Files: Shelf_001.glb [16.47MB] > /home/hooli/hooli/CAD/Shelf_001-transformed.glb [968.15KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Shelf_001-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.attach_1.geometry} material={materials.mat_0} position={[0, 0, -0.24]} />
      <mesh geometry={nodes.attach_2.geometry} material={materials.mat_0} position={[0.68, 0, -0.24]} />
      <mesh geometry={nodes.Shelf.geometry} material={materials.mat_0} scale={[1.4, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/Shelf_001-transformed.glb')
