/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Shelf_001.gltf --transform -j 
Files: Shelf_001.gltf [7.36KB] > C:\Users\Remes\hooli\public\Shelf_001\Shelf_001-transformed.glb [10.8KB] (-47%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Shelf_001-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, -0.24]}>
        <mesh geometry={nodes.attach_1_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_1_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_1_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_1_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_1_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_1_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.73, 0, -0.24]}>
        <mesh geometry={nodes.attach_2_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_6.geometry} material={materials.mat_0} />
      </group>
      <mesh geometry={nodes.Shelf_1.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Shelf_2.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Shelf_3.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Shelf_4.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Shelf_5.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Shelf_6.geometry} material={materials.mat_0} />
    </group>
  )
}

useGLTF.preload('/Shelf_001-transformed.glb')
