/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Shelf_001.glb --transform -j 
Files: Shelf_001.glb [24.05MB] > C:\Users\Remes\hooli\CAD\Shelf_001-transformed.glb [1.73MB] (93%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Shelf_001-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.attach_1.geometry} material={materials['Material.001']} position={[0, 0, -0.24]} />
      <mesh geometry={nodes.attach_2.geometry} material={materials['Material.001']} position={[0.73, 0, -0.24]} />
      <mesh geometry={nodes.Leikkauspinnat.geometry} material={materials['Material.002']} scale={[1.5, 1, 1]} />
      <mesh geometry={nodes.Suuret_pinnat.geometry} material={materials['Material.001']} scale={[1.5, 1, 1]} />
    </group>
  )
}

useGLTF.preload('/Shelf_001-transformed.glb')
