/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Hylly_008.glb --transform -j 
Files: Hylly_008.glb [16.48MB] > C:\Users\Remes\hooli\CAD\Hylly_008-transformed.glb [971.12KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Hylly_008-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.attach_left.geometry} material={materials.mat_0} position={[0, 0.387, -0.23]} />
      <mesh geometry={nodes.attach_right.geometry} material={materials.mat_0} position={[0.73, 0.387, -0.23]} />
      <mesh geometry={nodes.Left_door.geometry} material={materials.mat_0} position={[0.015, 0.013, -0.013]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Right_door.geometry} material={materials.mat_0} position={[0.375, 0.013, -0.013]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.runkoObj.geometry} material={materials.mat_0} />
    </group>
  )
}

useGLTF.preload('/Hylly_008-transformed.glb')
