/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Support_003.gltf --transform -j 
Files: Support_003.gltf [14.79KB] > C:\Users\Remes\hooli\CAD\Support_003-transformed.glb [16.72KB] (-13%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Support_003-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.01, 0, -0.25]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Main_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_6.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_7.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_8.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_9.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_10.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_11.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_12.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_13.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.03, 0.4, 0]}>
        <mesh geometry={nodes.attach_1_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_1_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_1_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_1_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_1_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_1_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.03, 0.8, 0]}>
        <mesh geometry={nodes.attach_2_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.03, 1.2, 0]}>
        <mesh geometry={nodes.attach_2_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.03, 1.6, 0]}>
        <mesh geometry={nodes.attach_2_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_6.geometry} material={materials.mat_0} />
      </group>
    </group>
  )
}

useGLTF.preload('/Support_003-transformed.glb')
