/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Support_020.glb --transform -j 
Files: Support_020.glb [16.5MB] > C:\Users\Remes\hooli\CAD\Support_020-transformed.glb [984.82KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Support_020-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.attach_1.geometry} material={materials['mat_0.012']} position={[-0.02, 0, 0]} />
      <mesh geometry={nodes.attach_10.geometry} material={materials['mat_0.012']} position={[-0.02, 0.9, 0]} />
      <mesh geometry={nodes.attach_11.geometry} material={materials['mat_0.012']} position={[-0.02, 1, 0]} />
      <mesh geometry={nodes.attach_12.geometry} material={materials['mat_0.012']} position={[-0.02, 1.1, 0]} />
      <mesh geometry={nodes.attach_13.geometry} material={materials['mat_0.012']} position={[-0.02, 1.2, 0]} />
      <mesh geometry={nodes.attach_14.geometry} material={materials['mat_0.012']} position={[-0.02, 1.3, 0]} />
      <mesh geometry={nodes.attach_15.geometry} material={materials['mat_0.012']} position={[-0.02, 1.4, 0]} />
      <mesh geometry={nodes.attach_16.geometry} material={materials['mat_0.012']} position={[-0.02, 1.5, 0]} />
      <mesh geometry={nodes.attach_17.geometry} material={materials['mat_0.012']} position={[-0.02, 1.6, 0]} />
      <mesh geometry={nodes.attach_18.geometry} material={materials['mat_0.012']} position={[-0.02, 1.7, 0]} />
      <mesh geometry={nodes.attach_19.geometry} material={materials['mat_0.012']} position={[-0.02, 1.8, 0]} />
      <mesh geometry={nodes.attach_2.geometry} material={materials['mat_0.012']} position={[-0.02, 0.1, 0]} />
      <mesh geometry={nodes.attach_20.geometry} material={materials['mat_0.012']} position={[-0.02, 1.9, 0]} />
      <mesh geometry={nodes.attach_3.geometry} material={materials['mat_0.012']} position={[-0.02, 0.2, 0]} />
      <mesh geometry={nodes.attach_4.geometry} material={materials['mat_0.012']} position={[-0.02, 0.3, 0]} />
      <mesh geometry={nodes.attach_5.geometry} material={materials['mat_0.012']} position={[-0.02, 0.4, 0]} />
      <mesh geometry={nodes.attach_6.geometry} material={materials['mat_0.012']} position={[-0.02, 0.5, 0]} />
      <mesh geometry={nodes.attach_7.geometry} material={materials['mat_0.012']} position={[-0.02, 0.6, 0]} />
      <mesh geometry={nodes.attach_8.geometry} material={materials['mat_0.012']} position={[-0.02, 0.7, 0]} />
      <mesh geometry={nodes.attach_9.geometry} material={materials['mat_0.012']} position={[-0.02, 0.8, 0]} />
      <mesh geometry={nodes.Main.geometry} material={materials['mat_0.012']} position={[0, 0, -0.25]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('/Support_020-transformed.glb')
