/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Support_007.gltf --transform -j 
Files: Support_007.gltf [21.62KB] > C:\Users\Remes\hooli\CAD\Support_007-transformed.glb [12.33KB] (43%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Support_007-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, -0.25]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Main_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_6.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_7.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.02, 0, 0]}>
        <mesh geometry={nodes.attach_1_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_1_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_1_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_1_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_1_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_1_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.02, 0.2, 0]}>
        <mesh geometry={nodes.attach_2_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.02, 0.4, 0]}>
        <mesh geometry={nodes.attach_2_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.02, 0.6, 0]}>
        <mesh geometry={nodes.attach_2_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.02, 0.8, 0]}>
        <mesh geometry={nodes.attach_2_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.02, 1, 0]}>
        <mesh geometry={nodes.attach_2_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.02, 1.2, 0]}>
        <mesh geometry={nodes.attach_2_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.02, 1.4, 0]}>
        <mesh geometry={nodes.attach_2_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_2_6.geometry} material={materials.mat_0} />
      </group>
    </group>
  )
}

useGLTF.preload('/Support_007-transformed.glb')
