/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Support_001.gltf --transform -j -D 
Files: Support_001.gltf [8.93KB] > C:\Users\Remes\hooli\public\Support_001\Support_001-transformed.glb [9.92KB] (-11%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Support_001-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.04, 0.85, 0.01]}>
        <mesh geometry={nodes.attach_bottom_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_bottom_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_bottom_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_bottom_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_bottom_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_bottom_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.04, 1.3, 0.01]}>
        <mesh geometry={nodes.attach_middle_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_middle_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_middle_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_middle_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_middle_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_middle_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.04, 1.75, 0.01]}>
        <mesh geometry={nodes.attach_middle_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_middle_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_middle_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_middle_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_middle_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_middle_6.geometry} material={materials.mat_0} />
      </group>
      <mesh geometry={nodes.Support_1.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Support_2.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Support_3.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Support_4.geometry} material={materials.mat_0} />
    </group>
  )
}

useGLTF.preload('/Support_001-transformed.glb')
