/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 hylly_001.gltf -j 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hylly_001.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.23, -0.23]}>
        <mesh geometry={nodes.attach_left_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_left_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_left_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_left_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_left_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_left_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.73, 0.23, -0.23]}>
        <mesh geometry={nodes.attach_right_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_right_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_right_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_right_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_right_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_right_6.geometry} material={materials.mat_0} />
      </group>
      <mesh geometry={nodes.Pohja_1.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_2.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_3.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_4.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_5.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_6.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_7.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_8.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_9.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_10.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_11.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_12.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_13.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_14.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_15.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_16.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_17.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_18.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_19.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_20.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_21.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_22.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_23.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_24.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_25.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_26.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_27.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_28.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_29.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_30.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_31.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_32.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_33.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_34.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_35.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_36.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_37.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_38.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_39.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_40.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_41.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_42.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_43.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_44.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_45.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_46.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_47.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_48.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_49.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_50.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_51.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_52.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_53.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_54.geometry} material={materials.mat_0} />
    </group>
  )
}

useGLTF.preload('/hylly_001.gltf')
