/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Support_009.gltf --transform -j 
Files: Support_009.gltf [14.69KB] > C:\Users\Remes\hooli\CAD\Support_009-transformed.glb [8.69KB] (41%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Support_009-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.02, 0.8, 0]}>
        <mesh geometry={nodes.attach_5_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.02, 0, 0]}>
        <mesh geometry={nodes.attach_5_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.02, 0.2, 0]}>
        <mesh geometry={nodes.attach_5_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.02, 0.4, 0]}>
        <mesh geometry={nodes.attach_5_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[-0.02, 0.6, 0]}>
        <mesh geometry={nodes.attach_5_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_5_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[0, 0, -0.25]} rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh geometry={nodes.Main_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_6.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.Main_7.geometry} material={materials.mat_0} />
      </group>
    </group>
  )
}

useGLTF.preload('/Support_009-transformed.glb')
