/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Hylly_007.glb --transform -j 
Files: Hylly_007.glb [16.47MB] > C:\Users\Remes\hooli\CAD\Hylly_007-transformed.glb [968.7KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Hylly_007-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.attach_left.geometry} material={materials.mat_0} position={[0, 0.23, -0.23]} />
      <mesh geometry={nodes.attach_right.geometry} material={materials.mat_0} position={[0.73, 0.23, -0.23]} />
      <mesh geometry={nodes.Pohja.geometry} material={materials.mat_0} />
    </group>
  )
}

useGLTF.preload('/Hylly_007-transformed.glb')
