/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Hylly_003.gltf --transform -j 
Files: Hylly_003.gltf [20.73KB] > C:\Users\Remes\hooli\CAD\Hylly_003-transformed.glb [30.14KB] (-45%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Hylly_003-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.08, -0.23]}>
        <mesh geometry={nodes.attach_left_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_left_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_left_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_left_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_left_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_left_6.geometry} material={materials.mat_0} />
      </group>
      <group position={[0.73, 0.08, -0.23]}>
        <mesh geometry={nodes.attach_right_1.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_right_2.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_right_3.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_right_4.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_right_5.geometry} material={materials.mat_0} />
        <mesh geometry={nodes.attach_right_6.geometry} material={materials.mat_0} />
      </group>
      <mesh geometry={nodes.Pohja_1.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_2.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_3.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_4.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_5.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_6.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_7.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_8.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_9.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_10.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_11.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_12.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_13.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_14.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_15.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_16.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_17.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_18.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_19.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_20.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_21.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_22.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_23.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_24.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_25.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_26.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_27.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_28.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_29.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_30.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_31.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_32.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_33.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_34.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_35.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_36.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_37.geometry} material={materials.mat_0} />
      <mesh geometry={nodes.Pohja_38.geometry} material={materials.mat_0} />
    </group>
  )
}

useGLTF.preload('/Hylly_003-transformed.glb')
