/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 CutSupport_001.glb --transform -j 
Files: CutSupport_001.glb [21.93KB] > C:\Users\Remes\hooli\CAD\CutSupport_001-transformed.glb [3.04KB] (86%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/CutSupport_001-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.attach_1.geometry} material={materials.mat_0} position={[-0.02, 0, 0]} />
      <mesh geometry={nodes.attach_17.geometry} material={materials.mat_0} position={[-0.02, 1.6, 0]} />
      <mesh geometry={nodes.attach_18.geometry} material={materials.mat_0} position={[-0.02, 1.7, 0]} />
      <mesh geometry={nodes.attach_19.geometry} material={materials.mat_0} position={[-0.02, 1.8, 0]} />
      <mesh geometry={nodes.attach_2.geometry} material={materials.mat_0} position={[-0.02, 0.1, 0]} />
      <mesh geometry={nodes.attach_20.geometry} material={materials.mat_0} position={[-0.02, 1.9, 0]} />
      <mesh geometry={nodes.attach_3.geometry} material={materials.mat_0} position={[-0.02, 0.2, 0]} />
      <mesh geometry={nodes.attach_4.geometry} material={materials.mat_0} position={[-0.02, 0.3, 0]} />
      <mesh geometry={nodes.attach_5.geometry} material={materials.mat_0} position={[-0.02, 0.4, 0]} />
      <mesh geometry={nodes.attach_6.geometry} material={materials.mat_0} position={[-0.02, 0.5, 0]} />
      <mesh geometry={nodes.Main_minus_Cut.geometry} material={materials.mat_0} />
    </group>
  )
}

useGLTF.preload('/CutSupport_001-transformed.glb')
