/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 CAD_kuppi-Kuppi_end.gltf --transform 
Files: CAD_kuppi-Kuppi_end.gltf [6.89KB] > C:\Users\Remes\hooli\src\3D_objektit\Kuppi_001\CAD_kuppi-Kuppi_end-transformed.glb [5.65KB] (18%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Kuppi_end-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Kuppi_end.geometry} material={materials.mat_0} />
    </group>
  )
}

useGLTF.preload('/Kuppi_end-transformed.glb')
